name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.3
          - 27.1
          - snapshot
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}
    - name: Set up Cask
      uses: conao3/setup-cask@master
    - name: Check out the source code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: cask install
    - name: Byte compile
      run: cask build
    - name: Run tests
      run: cask exec buttercup -L .
