name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.3
          - 27.1
          - snapshot
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Set up Jsonnet
      uses: zendesk/setup-jsonnet@v7
    - name: Set up Cask
      uses: conao3/setup-cask@master
    - name: Check out the source code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: cask install
    - name: Run tests before byte compilation
      run: UNDERCOVER_FORCE=true cask exec buttercup -L .
    - name: Byte compile
      run: cask build
    - name: Run tests after byte compilation
      run: cask exec buttercup -L .
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: emacs-${{ matrix.emacs_version }}
        parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
